tunnel: 67534728-9f06-4528-ae86-7f93a2286929
credentials-file: 67534728-9f06-4528-ae86-7f93a2286929.json
originRequest:
  noTLSVerify: true
ingress:
  - hostname: local-dev-app.sweepersmackdown.com
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true
  - hostname: local-dev-api.sweepersmackdown.com
    service: http://localhost:7071
    originRequest:
      noTLSVerify: true
  - hostname: local-dev-bot.sweepersmackdown.com
    service: http://localhost:7198
    originRequest:
      noTLSVerify: true
  - service: http_status:404
