@lobbyId = "lobbyId"

###

PUT http://localhost:7071/lobbies/{{lobbyId}}

{
}

###

PUT http://localhost:7071/lobbies/{{lobbyId}}

{
  "mode": 0,
  "height": 9,
  "width": 9,
  "mines": 10,
  "lives": 1,
  "timeLimit": 600
}

###
