@lobbyId = "lobbyId"
@newHostId = "userId2"

###

PATCH http://localhost:7071/lobbies/{{lobbyId}}

{
}

###

PATCH http://localhost:7071/lobbies/{{lobbyId}}

{
  "mode": 0,
  "height": 9,
  "width": 9,
  "mines": 10,
  "lives": 1,
  "timeLimit": 600,
  "boardCount": 2
}

###

PATCH http://localhost:7071/lobbies{{lobbyId}}

{
  "hostId": "{{newHostId}}"
}

###
